id: PA74D8881
initial_creation_type: ocr
source_metadata:
  volumes:
    62a977ca00ec40d99c0f2f741618247d:
      base_file: v024.txt
      image_group_id: I1PD95869
      title: གཤིན་རྗེ་གཤེད་ནག་པོའི་སྒྲུབ་ཐབས།
      total_pages: 1586
      volume_number: 24
